import { BaseEntity, QueryOptions } from '../../types';
import {
  DateFieldValue,
  NumberFieldValue,
  StringFieldValue,
  AllFieldValues,
} from '../../utils/queryBuilder';
import { Meta } from '../../types/collections';

/**
 * Interface for RSCollection[RS_ARPNotesXML]
 */
export interface RscollectionrsArpnotesxml {
  Meta?: Meta;
  items?: RsArpnotesxml[];
}

/**
 * Interface for RSCollection[extendedFieldDefinitions]
 */
export interface Rscollectionextendedfielddefinitions {
  Meta?: Meta;
  items?: ExtendedFieldDefinitions[];
}

/**
 * Interface for KeyValueParameter
 */
export interface KeyValueParameter {
  Name?: string;
  Value?: Object;
}

/**
 * Interface for ResultData
 */
export interface ResultData {
  Meta?: Meta;
  offset?: number;
  count?: number;
  totalCount?: number;
  limit?: number;
  first?: Meta;
  next?: Meta;
  previous?: Meta;
  items?: Object[];
}

/**
 * Interface for DBColumnProperties
 */
export interface Dbcolumnproperties {
  Meta?: Meta;
  ColumnName?: string;
  DataType?: string;
  MaximumCharacterLength?: string;
  NumericPrecision?: string;
  NumericPrecisionRadix?: string;
  NumericScale?: string;
  DatetimePrecision?: string;
  IsNullable?: string;
}

/**
 * RsArpnotesxml transaction line item
 *
 * Represents individual transaction records within a Arps collection.
 */
export interface RsArpnotesxml extends BaseEntity {
  CLIENTREF?: number;
  LINENUM?: number;
  LINE?: string;
}

/**
 * ExtendedFieldDefinitions transaction line item
 *
 * Represents individual transaction records within a Arps collection.
 */
export interface ExtendedFieldDefinitions extends BaseEntity {
  MODULENR?: number;
  LEVEL_?: number;
  PARENTREF?: number;
  OWNERREF?: number;
  TEXTFLDS1?: string;
  TEXTFLDS2?: string;
  TEXTFLDS3?: string;
  TEXTFLDS4?: string;
  TEXTFLDS5?: string;
  TEXTFLDS6?: string;
  TEXTFLDS7?: string;
  TEXTFLDS8?: string;
  TEXTFLDS9?: string;
  TEXTFLDS10?: string;
  TEXTFLDS11?: string;
  TEXTFLDS12?: string;
  TEXTFLDS13?: string;
  TEXTFLDS14?: string;
  TEXTFLDS15?: string;
  TEXTFLDS16?: string;
  TEXTFLDS17?: string;
  TEXTFLDS18?: string;
  TEXTFLDS19?: string;
  TEXTFLDS20?: string;
  TEXTFLDS21?: string;
  TEXTFLDS22?: string;
  TEXTFLDS23?: string;
  TEXTFLDS24?: string;
  TEXTFLDS25?: string;
  TEXTFLDS26?: string;
  TEXTFLDS27?: string;
  TEXTFLDS28?: string;
  TEXTFLDS29?: string;
  TEXTFLDS30?: string;
  TEXTFLDS31?: string;
  TEXTFLDS32?: string;
  TEXTFLDS33?: string;
  TEXTFLDS34?: string;
  TEXTFLDS35?: string;
  TEXTFLDS36?: string;
  TEXTFLDS37?: string;
  TEXTFLDS38?: string;
  TEXTFLDS39?: string;
  TEXTFLDS40?: string;
  TEXTFLDS41?: string;
  TEXTFLDS42?: string;
  TEXTFLDS43?: string;
  TEXTFLDS44?: string;
  TEXTFLDS45?: string;
  TEXTFLDS46?: string;
  TEXTFLDS47?: string;
  TEXTFLDS48?: string;
  TEXTFLDS49?: string;
  TEXTFLDS50?: string;
  NUMFLDS1?: number;
  NUMFLDS2?: number;
  NUMFLDS3?: number;
  NUMFLDS4?: number;
  NUMFLDS5?: number;
  NUMFLDS6?: number;
  NUMFLDS7?: number;
  NUMFLDS8?: number;
  NUMFLDS9?: number;
  NUMFLDS10?: number;
  NUMFLDS11?: number;
  NUMFLDS12?: number;
  NUMFLDS13?: number;
  NUMFLDS14?: number;
  NUMFLDS15?: number;
  NUMFLDS16?: number;
  NUMFLDS17?: number;
  NUMFLDS18?: number;
  NUMFLDS19?: number;
  NUMFLDS20?: number;
  NUMFLDS21?: number;
  NUMFLDS22?: number;
  NUMFLDS23?: number;
  NUMFLDS24?: number;
  NUMFLDS25?: number;
  NUMFLDS26?: number;
  NUMFLDS27?: number;
  NUMFLDS28?: number;
  NUMFLDS29?: number;
  NUMFLDS30?: number;
  NUMFLDS31?: number;
  NUMFLDS32?: number;
  NUMFLDS33?: number;
  NUMFLDS34?: number;
  NUMFLDS35?: number;
  NUMFLDS36?: number;
  NUMFLDS37?: number;
  NUMFLDS38?: number;
  NUMFLDS39?: number;
  NUMFLDS40?: number;
  NUMFLDS41?: number;
  NUMFLDS42?: number;
  NUMFLDS43?: number;
  NUMFLDS44?: number;
  NUMFLDS45?: number;
  NUMFLDS46?: number;
  NUMFLDS47?: number;
  NUMFLDS48?: number;
  NUMFLDS49?: number;
  NUMFLDS50?: number;
}

/**
 * Arps entity interface based on swagger definition
 */
export interface Arps extends BaseEntity {
  ACCOUNT_TYPE?: number;
  CODE?: string;
  TITLE?: string;
  AUXIL_CODE?: string;
  AUTH_CODE?: string;
  ADDRESS1?: string;
  ADDRESS2?: string;
  DISTRICT_CODE?: string;
  DISTRICT?: string;
  TOWN_CODE?: string;
  TOWN?: string;
  CITY_CODE?: string;
  CITY?: string;
  COUNTRY_CODE?: string;
  COUNTRY?: string;
  POSTAL_CODE?: string;
  TELEPHONE1?: string;
  TELEPHONE1_CODE?: string;
  TELEPHONE2?: string;
  TELEPHONE2_CODE?: string;
  FAX?: string;
  FAX_CODE?: string;
  TAX_ID?: string;
  TAX_OFFICE?: string;
  TAX_OFFICE_CODE?: string;
  CONTACT?: string;
  DISCOUNT_RATE?: number;
  EXTENREF?: number;
  PAYMENT_CODE?: string;
  PAYMENTREF?: number;
  E_MAIL?: string;
  WEB_URL?: string;
  FACEBOOK_URL?: string;
  TWITTER_URL?: string;
  APPLE_ID?: string;
  SKYPE_ID?: string;
  REMINDER_TYPE?: number;
  REMINDER_EMAIL?: string;
  REMINDER_FAX?: string;
  CORRESP_LANG?: number;
  VAT_ID?: string;
  BLOCKED?: number;
  BANK_ID1?: string;
  BANK_ID2?: string;
  BANK_ID3?: string;
  BANK_ID4?: string;
  BANK_ID5?: string;
  BANK_ID6?: string;
  BANK_ID7?: string;
  BANK_NAME1?: string;
  BANK_NAME2?: string;
  BANK_NAME3?: string;
  BANK_NAME4?: string;
  BANK_NAME5?: string;
  BANK_NAME6?: string;
  BANK_NAME7?: string;
  BANK_ACCOUNT1?: string;
  BANK_ACCOUNT2?: string;
  BANK_ACCOUNT3?: string;
  BANK_ACCOUNT4?: string;
  BANK_ACCOUNT5?: string;
  BANK_ACCOUNT6?: string;
  BANK_ACCOUNT7?: string;
  DELIVERY_METHOD?: string;
  SHIPMENT_AGENT?: string;
  CURRENCY?: number;
  E_COMM_ID?: string;
  TRADING_GRP?: string;
  DEBT_TRCK_TYPE?: number;
  XRTDIF_TYPE?: number;
  NOTES?: RscollectionrsArpnotesxml;
  CREDIT_TYPE?: number;
  CREDIT_LIMIT?: number;
  CREDIT_BALANCED?: number;
  RISKFACT_CHQ?: number;
  RISKFACT_PROMNT?: number;
  ACTION_CREDHOLD?: number;
  XBUFS?: string;
  GL_CODE?: string;
  ACCOUNTREF?: number;
  OHP_CODE?: string;
  CENTERREF?: number;
  PROJECT_CODE?: string;
  PROJECTREF?: number;
  FLDALS?: string;
  ITEXT?: string;
  LANGP?: string;
  PP_GROUP_CODE?: string;
  USE_REP_RISK?: number;
  RISK_LIMIT?: number;
  RISK_BALANCED?: number;
  ORD_SEND_METHOD?: number;
  ORD_SEND_EMAIL?: string;
  ORD_SEND_FAX?: string;
  DSP_SEND_METHOD?: number;
  DSP_SEND_EMAIL?: string;
  DSP_SEND_FAX?: string;
  INV_SEND_METHOD?: number;
  INV_SEND_EMAIL?: string;
  INV_SEND_FAX?: string;
  SUBSCRIBER_STATUS?: number;
  SUBSCRIBER_EXT?: string;
  AUTO_PAID_BANK?: string;
  PAYMENT_TYPE?: number;
  LAST_SEND_REM_LEV?: number;
  EXT_ACC_FLAGS?: number;
  ORD_SEND_FORMAT?: number;
  DSP_SEND_FORMAT?: number;
  INV_SEND_FORMAT?: number;
  REM_SEND_FORMAT?: number;
  STORE_CREDIT_CARD_NO?: string;
  CL_ORD_FREQ?: number;
  ORD_DAY?: number;
  LOGOID?: string;
  LID_Confirmed?: number;
  E_BSNS_SEND_TYPE?: number;
  LDX_DEF_ORDER_STAT?: number;
  LDX_DEF_ORDER_PRC?: number;
  ITR_SEND_METHOD?: number;
  ITR_SEND_MAIL_ADR?: string;
  ITR_SEND_FAX?: string;
  ITR_SEND_FORMAT?: number;
  IMG2INC?: number;
  CELL_PHONE?: string;
  INVOICE_PRNT_CNT?: number;
  GENIUSFLDSLIST?: Rscollectionextendedfielddefinitions;
  DEFNFLDSLIST?: Rscollectionextendedfielddefinitions;
  WFLOWCARDREF?: number;
  PARENTCLCODE?: string;
  PARENTCLREF?: number;
  CODE_CHANGED?: number;
  COLLECTINV?: number;
  PIECEORDINFLICT?: number;
  ORGLOGOID?: string;
  PURCHBRWS?: number;
  SALESBRWS?: number;
  IMPBRWS?: number;
  EXPBRWS?: number;
  FINBRWS?: number;
  COLLATRLRISK_TYPE?: number;
  COLLRISK_OVER?: number;
  COLLRISK_ORD_RISK_OVER?: number;
  COLLRISK_DESP_RISK_OVER?: number;
  COLLRISK_USE_REP_RISK?: number;
  COLLRISK_PCOLLATRL_TOTAL?: number;
  COLLRISK_REP_PCOLLATRL_TOT?: number;
  COLLRISK_SCOLLATRL_TOTAL?: number;
  COLLRISK_TOTAL?: number;
  COLLRISK_REP_RISK_TOTAL?: number;
  COLLRISK_DESP_TOTAL?: number;
  COLLRISK_REP_DESP_RISK_TOT?: number;
  COLLRISK_LIMIT?: number;
  COLLRISK_REP_LIMIT?: number;
  COLLRISK_BALANCED?: number;
  COLLRISK_REP_BALANCED?: number;
  COLLRISK_ORD_RISK_TOTAL?: number;
  COLLRISK_REP_ORD_RISK_TOT?: number;
  COLLRISK_ORD_RISK_TOT_SUGG?: number;
  COLLRISK_REP_ORD_RISK_TOT_SUG?: number;
  COLLRISK_SEP_CS_RISK_TOT?: number;
  COLLRISK_CS_RISK_OVER?: number;
  COLLRISK_CS_RISK_TOTAL?: number;
  COLLRISK_REP_CS_RISK_TOT?: number;
  GRPFIRMNR?: number;
  CONSCODEREF?: number;
  CONSCODE?: string;
  AUXIL_CODE2?: string;
  AUXIL_CODE3?: string;
  AUXIL_CODE4?: string;
  AUXIL_CODE5?: string;
  EBANKCODE?: number;
  OFF_SEND_METHOD?: number;
  OFF_SEND_MAIL_ADDR?: string;
  OFF_SEND_FAX?: string;
  OFF_SEND_FORMAT?: number;
  RISK_TYPE1?: number;
  RISK_TYPE2?: number;
  RISK_TYPE3?: number;
  RISK_TYPE4?: number;
  RISK_TYPE5?: number;
  RISK_TYPE6?: number;
  RISK_TYPE7?: number;
  RISK_TYPE8?: number;
  RISK_TYPE9?: number;
  RISK_TYPE10?: number;
  RISK_TYPE11?: number;
  RISK_TYPE12?: number;
  RISK_TYPE13?: number;
  RISK_TYPE14?: number;
  RISK_TYPE15?: number;
  CST_CEK_RISK_FACTOR?: number;
  CST_SENET_RISK_FACTOR?: number;
  RISK_GRP_CONTROL?: number;
  ACTION_CREDHOLD_ORD?: number;
  ACTION_CREDHOLD_DESP?: number;
  ACTION_CREDHOLD_ACC?: number;
  ACTION_CREDHOLD_CST_CS?: number;
  ACTION_CREDHOLD_MY_CS?: number;
  RISK_CTRL_TYPE?: number;
  ACC_RISK_TOTAL?: number;
  REP_ACC_RISK_TOTAL?: number;
  CST_CS_RISK_TOTAL?: number;
  REP_CST_CS_RISK_TOTAL?: number;
  MY_CS_RISK_TOTAL?: number;
  REP_MY_CS_RISK_TOTAL?: number;
  ORD_RISK_TOTAL?: number;
  REP_ORD_RISK_TOTAL?: number;
  ORD_RISK_TOTAL_SUGG?: number;
  REP_ORD_RISK_TOTAL_SUGG?: number;
  DESP_RISK_TOTAL?: number;
  REP_DESP_RISK_TOTAL?: number;
  ACC_RISK_LIMIT?: number;
  REP_ACC_RISK_LIMIT?: number;
  CST_CS_RISK_LIMIT?: number;
  REP_CST_CS_RISK_LIMIT?: number;
  MY_CS_RISK_LIMIT?: number;
  REP_MY_CS_RISK_LIMIT?: number;
  DESP_RISK_LIMIT?: number;
  REP_DESP_RISK_LIMIT?: number;
  ORD_RISK_LIMIT?: number;
  REP_ORD_RISK_LIMIT?: number;
  ORD_RISK_LIMIT_SUGG?: number;
  REP_ORD_SIRK_LIMIT_SUGG?: number;
  ACC_RISK_BALANCED?: number;
  REP_ACC_RISK_BALANCED?: number;
  CST_CS_RISK_BALANCED?: number;
  REP_CST_CS_RISK_BALANCED?: number;
  MY_CS_RISK_BALANCED?: number;
  REP_MY_CS_RISK_BALANCED?: number;
  DESP_RISK_BALANCED?: number;
  REP_DESP_RISK_BALANCED?: number;
  ORD_RISK_BALANCED?: number;
  REP_ORD_RISK_BALANCED?: number;
  ORD_RISK_BALANCED_SUGG?: number;
  REP_ORD_RISK_BALANCED_SUGG?: number;
  LOAN_GRP_CTRL?: number;
  EBUS_DATA_SEND_TYPE?: number;
  INI_STATUS_FLAGS?: number;
  SLS_ORDER_STATUS?: number;
  SLS_ORDER_PRICE?: number;
  SAME_ITEM_CODE_USE?: number;
  IMAGE?: string;
  IMAGE_SIZE?: number;
  MAP_ID?: string;
  LONGITUDE?: string;
  LATITUDE?: string;
  CITY_ID?: string;
  TOWN_ID?: string;
  BANK_IBAN1?: string;
  BANK_IBAN2?: string;
  BANK_IBAN3?: string;
  BANK_IBAN4?: string;
  BANK_IBAN5?: string;
  BANK_IBAN6?: string;
  BANK_IBAN7?: string;
  BANK_BIC1?: string;
  BANK_BIC2?: string;
  BANK_BIC3?: string;
  BANK_BIC4?: string;
  BANK_BIC5?: string;
  BANK_BIC6?: string;
  BANK_BIC7?: string;
  PERSCOMPANY?: number;
  TCKNO?: string;
  EXT_SEND_METHOD?: number;
  EXT_SEND_EMAIL?: string;
  EXT_SEND_FAX?: string;
  EXT_SEND_FORMAT?: number;
  ADDTOREFLIST?: number;
  ORD_RISK_OVER_SUGG?: number;
  CASH_CODE?: string;
  CASHREF?: number;
  USED_IN_PERIODS?: number;
  CONTACT2?: string;
  CONTACT3?: string;
  E_MAIL2?: string;
  E_MAIL3?: string;
  CONTACT1_TEL_CODE?: string;
  CONTACT2_TEL_CODE?: string;
  CONTACT3_TEL_CODE?: string;
  CONTACT1_TEL?: string;
  CONTACT2_TEL?: string;
  CONTACT3_TEL?: string;
  CONTACT1_TEL_EXT?: string;
  CONTACT2_TEL_EXT?: string;
  CONTACT3_TEL_EXT?: string;
  RSKLIM_CNTRL?: number;
  DUEDATE_CNTRL?: number;
  AGING_CNTRL?: number;
  AGING_DAY?: number;
  ORD_PRIORITY?: number;
  ACCEPT_EINV?: number;
  EIVOICEID?: string;
  PROFILE_ID?: number;
  PURC_ORDER_STATUS?: number;
  PURC_ORDER_PRICE?: number;
  BANK_CURR1?: string;
  BANK_CURR2?: string;
  BANK_CURR3?: string;
  BANK_CURR4?: string;
  BANK_CURR5?: string;
  BANK_CURR6?: string;
  BANK_CURR7?: string;
  CS_DOWNS_RISK?: number;
  CST_CS_CIRO_RISK_OVER?: number;
  CST_CIRO_CEK_RISK_FAC?: number;
  CST_CIRO_SENET_RISK_FAC?: number;
  CS_CIRO_DOWNS_RISK?: number;
  CST_CS_CIRO_RISK_LIMIT?: number;
  REP_CST_CS_CIRO_RISK_LIMIT?: number;
  CST_CS_CIRO_RISK_BALANCED?: number;
  REP_CST_CS_CIRO_RISK_BALANCED?: number;
  CST_CS_OWN_RISK_TOTAL?: number;
  REP_CST_CS_OWN_RISK_TOTAL?: number;
  CST_CS_CIRO_RISK_TOTAL?: number;
  REP_CST_CS_CIRO_RISK_TOTAL?: number;
  DESP_RISK_OVER_SUGG?: number;
  DESP_RISK_LIMIT_SUGG?: number;
  REP_DESP_RISK_LIMIT_SUGG?: number;
  DESP_RISK_TOTAL_SUGG?: number;
  REP_DESP_RISK_TOTAL_SUGG?: number;
  DESP_RISK_BALANCED_SUGG?: number;
  REP_DESP_RISK_BALANCED_SUGG?: number;
  DBS_LIMIT1?: number;
  DBS_LIMIT2?: number;
  DBS_LIMIT3?: number;
  DBS_LIMIT4?: number;
  DBS_LIMIT5?: number;
  DBS_LIMIT6?: number;
  DBS_LIMIT7?: number;
  DBS_TOTAL1?: number;
  DBS_TOTAL2?: number;
  DBS_TOTAL3?: number;
  DBS_TOTAL4?: number;
  DBS_TOTAL5?: number;
  DBS_TOTAL6?: number;
  DBS_TOTAL7?: number;
  DBS_BANKNO1?: number;
  DBS_BANKNO2?: number;
  DBS_BANKNO3?: number;
  DBS_BANKNO4?: number;
  DBS_BANKNO5?: number;
  DBS_BANKNO6?: number;
  DBS_BANKNO7?: number;
  DBS_RSKCTRL1?: number;
  DBS_RSKCTRL2?: number;
  DBS_RSKCTRL3?: number;
  DBS_RSKCTRL4?: number;
  DBS_RSKCTRL5?: number;
  DBS_RSKCTRL6?: number;
  DBS_RSKCTRL7?: number;
  DBS_CURR1?: number;
  DBS_CURR2?: number;
  DBS_CURR3?: number;
  DBS_CURR4?: number;
  DBS_CURR5?: number;
  DBS_CURR6?: number;
  DBS_CURR7?: number;
  BANK_CORRP_ACC1?: string;
  BANK_CORRP_ACC2?: string;
  BANK_CORRP_ACC3?: string;
  BANK_CORRP_ACC4?: string;
  BANK_CORRP_ACC5?: string;
  BANK_CORRP_ACC6?: string;
  BANK_CORRP_ACC7?: string;
  BANK_VOEN1?: string;
  BANK_VOEN2?: string;
  BANK_VOEN3?: string;
  BANK_VOEN4?: string;
  BANK_VOEN5?: string;
  BANK_VOEN6?: string;
  BANK_VOEN7?: string;
  EINVOICE_TYPE?: number;
  EARCHIVE_SEND_MODE?: number;
  EARCHIVE_IS_RETAIL_AR_AP?: number;
  TITLE2?: string;
  TELEPHONE_EXTENSION1?: string;
  TELEPHONE_EXTENSION2?: string;
  FAX_EXTENSION?: string;
  GLOBAL_ID?: string;
  ISFOREIGN?: number;
  POST_LABEL?: string;
  SENDER_LABEL?: string;
  DEG_ACTIVE?: number;
  DEG_CURR?: number;
  NAME?: string;
  SURNAME?: string;
  LABEL_INFO?: number;
  DUE_DATE_CONTOL1?: number;
  DUE_DATE_CONTOL2?: number;
  DUE_DATE_CONTOL3?: number;
  DUE_DATE_CONTOL4?: number;
  DUE_DATE_CONTOL5?: number;
  DUE_DATE_CONTOL6?: number;
  DUE_DATE_CONTOL7?: number;
  DUE_DATE_CONTOL8?: number;
  DUE_DATE_CONTOL9?: number;
  DUE_DATE_CONTOL10?: number;
  DUE_DATE_CONTOL11?: number;
  DUE_DATE_CONTOL12?: number;
  DUE_DATE_CONTOL13?: number;
  DUE_DATE_CONTOL14?: number;
  DUE_DATE_CONTOL15?: number;
  DUE_DATE_COUNT?: number;
  DUE_DATE_LIMIT?: number;
  DUE_DATE_TRACK?: number;
  CLOSE_DATE_COUNT?: number;
  CLOSE_DATE_TRACK?: number;
  DEFBNACCREF?: number;
  DEFAULT_BANKACC_CODE?: string;
  CURR_RATE_TYPE?: number;
  INSTEAD_OF_DISPATCH?: number;
  EINV_EARC_TYPE?: number;
  ADDRESS_NO?: string;
  FBS_SEND_METHOD?: number;
  FBS_SEND_EMAILADDR?: string;
  FBS_SEND_FORMAT?: number;
  FBS_SEND_FAXNR?: string;
  FBA_SEND_METHOD?: number;
  FBA_SEND_EMAILADDR?: string;
  FBA_SEND_FORMAT?: number;
  FBA_SEND_FAXNR?: string;
  SECTOR_MAIN_REF?: number;
  SECTOR_MAIN_CODE?: string;
  SECTOR_SUB_REF?: number;
  SECTOR_SUB_CODE?: string;
  PERSONEL_COSTS?: number;
  EARC_EMAIL_ADDRESS1?: string;
  EARC_EMAIL_ADDRESS2?: string;
  EARC_EMAIL_ADDRESS3?: string;
  FACTORY_DIV_NR?: number;
  FACTORY_NR?: number;
  IN_INVEN_NR?: number;
  OUT_INVEN_NR?: number;
  QTY_DEP_DURATION?: number;
  QTY_IN_DEP_DURATION?: number;
  OVER_LAP_TYPE?: number;
  OVER_LAP_AMOUNT?: number;
  OVER_LAP_PERC?: number;
  BROKER_COMP?: number;
  CREATE_WH_FICHE?: number;
  EINV_CUSTOMS?: number;
  SUB_CONT?: number;
  ACCEPT_DESP?: number;
  PROFILEID_DESP?: number;
  LABEL_INFO_DESP?: number;
  POST_LABEL_CODE_DESP?: string;
  SENDER_LABEL_CODE_DESP?: string;
  ACCEPT_EINV_PUBLIC?: number;
  PUBLICBNACCREF?: number;
  PUBLIC_BNACC_CODE?: string;
  PUBLIC_BNACC_IBAN?: string;
  PUBLIC_BNACC_CURRENCY?: number;
  KVKK_PERM_STATUS?: number;
  KVKK_BEGIN_DATE?: string;
  KVKK_END_DATE?: string;
  KVKK_CANCEL_DATE?: string;
  KVKK_ANONYMIZE_STATUS?: number;
  KVKK_ANONYMIZE_DATE?: string;
  EXIM_SEND_METHOD?: number;
  EXIM_SEND_EMAILADR?: string;
  EXIM_SEND_FORMAT?: number;
  EXIM_SEND_FAXNR?: string;
  CAN_DEDUCT?: number;
  DRIVERREF?: number;
  EX_COUNTRY_TYPE?: number;
  EX_COUNTRYREF?: number;
  EX_COUNTRY_CODE?: string;
  EX_COUNTRY_NAME?: string;
  IM_COUNTRY_TYPE?: number;
  IM_COUNTRYREF?: number;
  IM_COUNTRY_CODE?: string;
  IM_COUNTRY_NAME?: string;
  EXIM_PAYTYPEREF?: number;
  EXIM_PAYTYPE_CODE?: string;
  EXIM_BRBANKREF?: number;
  EXIM_BRBANK_CODE?: string;
  EXIM_CUSTOMREF?: number;
  EXIM_CUSTOM_CODE?: string;
  EXIM_REGTYPEREF?: number;
  EXIM_REGTYPE_CODE?: string;
  EXIM_NOTIFYCLREF?: number;
  EXIM_NOTIFY_ARPCODE?: string;
  EXIM_CONSULTCLREF?: number;
  EXIM_CONSULT_ARPCODE?: string;
  EXIM_FREIGHTCLREF?: number;
  EXIM_FREIGHT_ARPCODE?: string;
  DISP_PRINT_CNT?: number;
  ORD_PRINT_CNT?: number;
  GUID?: string;
  CLPTYPEFORPPAYDT?: number;
  CLSTYPEFORPPAYDT?: number;
  MERSIS_NO?: string;
  COMM_RECORD_NO?: string;
  LOW_LEVEL_CODES1?: number;
  LOW_LEVEL_CODES2?: number;
  LOW_LEVEL_CODES3?: number;
  LOW_LEVEL_CODES4?: number;
  LOW_LEVEL_CODES5?: number;
  LOW_LEVEL_CODES6?: number;
  LOW_LEVEL_CODES7?: number;
  LOW_LEVEL_CODES8?: number;
  LOW_LEVEL_CODES9?: number;
  LOW_LEVEL_CODES10?: number;
  INSTAGRAMURL?: string;
  LINKEDINURL?: string;
  WHATSAPPID?: string;
}

/**
 * Union type of all Arps field names for type-safe field selection and sorting
 */
export type ArpsField =
  | 'INTERNAL_REFERENCE'
  | 'RECORD_STATUS'
  | 'ACCOUNT_TYPE'
  | 'CODE'
  | 'TITLE'
  | 'AUXIL_CODE'
  | 'AUTH_CODE'
  | 'ADDRESS1'
  | 'ADDRESS2'
  | 'DISTRICT_CODE'
  | 'DISTRICT'
  | 'TOWN_CODE'
  | 'TOWN'
  | 'CITY_CODE'
  | 'CITY'
  | 'COUNTRY_CODE'
  | 'COUNTRY'
  | 'POSTAL_CODE'
  | 'TELEPHONE1'
  | 'TELEPHONE1_CODE'
  | 'TELEPHONE2'
  | 'TELEPHONE2_CODE'
  | 'FAX'
  | 'FAX_CODE'
  | 'TAX_ID'
  | 'TAX_OFFICE'
  | 'TAX_OFFICE_CODE'
  | 'CONTACT'
  | 'DISCOUNT_RATE'
  | 'EXTENREF'
  | 'PAYMENT_CODE'
  | 'PAYMENTREF'
  | 'E_MAIL'
  | 'WEB_URL'
  | 'FACEBOOK_URL'
  | 'TWITTER_URL'
  | 'APPLE_ID'
  | 'SKYPE_ID'
  | 'REMINDER_TYPE'
  | 'REMINDER_EMAIL'
  | 'REMINDER_FAX'
  | 'CORRESP_LANG'
  | 'VAT_ID'
  | 'BLOCKED'
  | 'BANK_ID1'
  | 'BANK_ID2'
  | 'BANK_ID3'
  | 'BANK_ID4'
  | 'BANK_ID5'
  | 'BANK_ID6'
  | 'BANK_ID7'
  | 'BANK_NAME1'
  | 'BANK_NAME2'
  | 'BANK_NAME3'
  | 'BANK_NAME4'
  | 'BANK_NAME5'
  | 'BANK_NAME6'
  | 'BANK_NAME7'
  | 'BANK_ACCOUNT1'
  | 'BANK_ACCOUNT2'
  | 'BANK_ACCOUNT3'
  | 'BANK_ACCOUNT4'
  | 'BANK_ACCOUNT5'
  | 'BANK_ACCOUNT6'
  | 'BANK_ACCOUNT7'
  | 'DELIVERY_METHOD'
  | 'SHIPMENT_AGENT'
  | 'CURRENCY'
  | 'TEXTINC'
  | 'DATA_SITEID'
  | 'DATA_REFERENCE'
  | 'E_COMM_ID'
  | 'TRADING_GRP'
  | 'CREATED_BY'
  | 'DATE_CREATED'
  | 'HOUR_CREATED'
  | 'MIN_CREATED'
  | 'SEC_CREATED'
  | 'MODIFIED_BY'
  | 'DATE_MODIFIED'
  | 'HOUR_MODIFIED'
  | 'MIN_MODIFIED'
  | 'SEC_MODIFIED'
  | 'DEBT_TRCK_TYPE'
  | 'XRTDIF_TYPE'
  | 'NOTES'
  | 'CREDIT_TYPE'
  | 'CREDIT_LIMIT'
  | 'CREDIT_BALANCED'
  | 'RISKFACT_CHQ'
  | 'RISKFACT_PROMNT'
  | 'ACTION_CREDHOLD'
  | 'XBUFS'
  | 'GL_CODE'
  | 'ACCOUNTREF'
  | 'OHP_CODE'
  | 'CENTERREF'
  | 'PROJECT_CODE'
  | 'PROJECTREF'
  | 'FLDALS'
  | 'ITEXT'
  | 'LANGP'
  | 'PP_GROUP_CODE'
  | 'XML_ATTRIBUTE'
  | 'USE_REP_RISK'
  | 'RISK_LIMIT'
  | 'RISK_BALANCED'
  | 'ORD_SEND_METHOD'
  | 'ORD_SEND_EMAIL'
  | 'ORD_SEND_FAX'
  | 'DSP_SEND_METHOD'
  | 'DSP_SEND_EMAIL'
  | 'DSP_SEND_FAX'
  | 'INV_SEND_METHOD'
  | 'INV_SEND_EMAIL'
  | 'INV_SEND_FAX'
  | 'SUBSCRIBER_STATUS'
  | 'SUBSCRIBER_EXT'
  | 'AUTO_PAID_BANK'
  | 'PAYMENT_TYPE'
  | 'LAST_SEND_REM_LEV'
  | 'EXT_ACC_FLAGS'
  | 'ORD_SEND_FORMAT'
  | 'DSP_SEND_FORMAT'
  | 'INV_SEND_FORMAT'
  | 'REM_SEND_FORMAT'
  | 'STORE_CREDIT_CARD_NO'
  | 'CL_ORD_FREQ'
  | 'ORD_DAY'
  | 'LOGOID'
  | 'LID_Confirmed'
  | 'E_BSNS_SEND_TYPE'
  | 'LDX_DEF_ORDER_STAT'
  | 'LDX_DEF_ORDER_PRC'
  | 'ITR_SEND_METHOD'
  | 'ITR_SEND_MAIL_ADR'
  | 'ITR_SEND_FAX'
  | 'ITR_SEND_FORMAT'
  | 'IMG2INC'
  | 'CELL_PHONE'
  | 'INVOICE_PRNT_CNT'
  | 'GENIUSFLDSLIST'
  | 'DEFNFLDSLIST'
  | 'WFLOWCARDREF'
  | 'PARENTCLCODE'
  | 'PARENTCLREF'
  | 'CODE_CHANGED'
  | 'COLLECTINV'
  | 'PIECEORDINFLICT'
  | 'ORGLOGOID'
  | 'PURCHBRWS'
  | 'SALESBRWS'
  | 'IMPBRWS'
  | 'EXPBRWS'
  | 'FINBRWS'
  | 'COLLATRLRISK_TYPE'
  | 'COLLRISK_OVER'
  | 'COLLRISK_ORD_RISK_OVER'
  | 'COLLRISK_DESP_RISK_OVER'
  | 'COLLRISK_USE_REP_RISK'
  | 'COLLRISK_PCOLLATRL_TOTAL'
  | 'COLLRISK_REP_PCOLLATRL_TOT'
  | 'COLLRISK_SCOLLATRL_TOTAL'
  | 'COLLRISK_TOTAL'
  | 'COLLRISK_REP_RISK_TOTAL'
  | 'COLLRISK_DESP_TOTAL'
  | 'COLLRISK_REP_DESP_RISK_TOT'
  | 'COLLRISK_LIMIT'
  | 'COLLRISK_REP_LIMIT'
  | 'COLLRISK_BALANCED'
  | 'COLLRISK_REP_BALANCED'
  | 'COLLRISK_ORD_RISK_TOTAL'
  | 'COLLRISK_REP_ORD_RISK_TOT'
  | 'COLLRISK_ORD_RISK_TOT_SUGG'
  | 'COLLRISK_REP_ORD_RISK_TOT_SUG'
  | 'COLLRISK_SEP_CS_RISK_TOT'
  | 'COLLRISK_CS_RISK_OVER'
  | 'COLLRISK_CS_RISK_TOTAL'
  | 'COLLRISK_REP_CS_RISK_TOT'
  | 'GRPFIRMNR'
  | 'CONSCODEREF'
  | 'CONSCODE'
  | 'AUXIL_CODE2'
  | 'AUXIL_CODE3'
  | 'AUXIL_CODE4'
  | 'AUXIL_CODE5'
  | 'EBANKCODE'
  | 'OFF_SEND_METHOD'
  | 'OFF_SEND_MAIL_ADDR'
  | 'OFF_SEND_FAX'
  | 'OFF_SEND_FORMAT'
  | 'RISK_TYPE1'
  | 'RISK_TYPE2'
  | 'RISK_TYPE3'
  | 'RISK_TYPE4'
  | 'RISK_TYPE5'
  | 'RISK_TYPE6'
  | 'RISK_TYPE7'
  | 'RISK_TYPE8'
  | 'RISK_TYPE9'
  | 'RISK_TYPE10'
  | 'RISK_TYPE11'
  | 'RISK_TYPE12'
  | 'RISK_TYPE13'
  | 'RISK_TYPE14'
  | 'RISK_TYPE15'
  | 'CST_CEK_RISK_FACTOR'
  | 'CST_SENET_RISK_FACTOR'
  | 'RISK_GRP_CONTROL'
  | 'ACTION_CREDHOLD_ORD'
  | 'ACTION_CREDHOLD_DESP'
  | 'ACTION_CREDHOLD_ACC'
  | 'ACTION_CREDHOLD_CST_CS'
  | 'ACTION_CREDHOLD_MY_CS'
  | 'RISK_CTRL_TYPE'
  | 'ACC_RISK_TOTAL'
  | 'REP_ACC_RISK_TOTAL'
  | 'CST_CS_RISK_TOTAL'
  | 'REP_CST_CS_RISK_TOTAL'
  | 'MY_CS_RISK_TOTAL'
  | 'REP_MY_CS_RISK_TOTAL'
  | 'ORD_RISK_TOTAL'
  | 'REP_ORD_RISK_TOTAL'
  | 'ORD_RISK_TOTAL_SUGG'
  | 'REP_ORD_RISK_TOTAL_SUGG'
  | 'DESP_RISK_TOTAL'
  | 'REP_DESP_RISK_TOTAL'
  | 'ACC_RISK_LIMIT'
  | 'REP_ACC_RISK_LIMIT'
  | 'CST_CS_RISK_LIMIT'
  | 'REP_CST_CS_RISK_LIMIT'
  | 'MY_CS_RISK_LIMIT'
  | 'REP_MY_CS_RISK_LIMIT'
  | 'DESP_RISK_LIMIT'
  | 'REP_DESP_RISK_LIMIT'
  | 'ORD_RISK_LIMIT'
  | 'REP_ORD_RISK_LIMIT'
  | 'ORD_RISK_LIMIT_SUGG'
  | 'REP_ORD_SIRK_LIMIT_SUGG'
  | 'ACC_RISK_BALANCED'
  | 'REP_ACC_RISK_BALANCED'
  | 'CST_CS_RISK_BALANCED'
  | 'REP_CST_CS_RISK_BALANCED'
  | 'MY_CS_RISK_BALANCED'
  | 'REP_MY_CS_RISK_BALANCED'
  | 'DESP_RISK_BALANCED'
  | 'REP_DESP_RISK_BALANCED'
  | 'ORD_RISK_BALANCED'
  | 'REP_ORD_RISK_BALANCED'
  | 'ORD_RISK_BALANCED_SUGG'
  | 'REP_ORD_RISK_BALANCED_SUGG'
  | 'LOAN_GRP_CTRL'
  | 'EBUS_DATA_SEND_TYPE'
  | 'INI_STATUS_FLAGS'
  | 'SLS_ORDER_STATUS'
  | 'SLS_ORDER_PRICE'
  | 'SAME_ITEM_CODE_USE'
  | 'IMAGE'
  | 'IMAGE_SIZE'
  | 'MAP_ID'
  | 'LONGITUDE'
  | 'LATITUDE'
  | 'CITY_ID'
  | 'TOWN_ID'
  | 'BANK_IBAN1'
  | 'BANK_IBAN2'
  | 'BANK_IBAN3'
  | 'BANK_IBAN4'
  | 'BANK_IBAN5'
  | 'BANK_IBAN6'
  | 'BANK_IBAN7'
  | 'BANK_BIC1'
  | 'BANK_BIC2'
  | 'BANK_BIC3'
  | 'BANK_BIC4'
  | 'BANK_BIC5'
  | 'BANK_BIC6'
  | 'BANK_BIC7'
  | 'PERSCOMPANY'
  | 'TCKNO'
  | 'EXT_SEND_METHOD'
  | 'EXT_SEND_EMAIL'
  | 'EXT_SEND_FAX'
  | 'EXT_SEND_FORMAT'
  | 'ADDTOREFLIST'
  | 'ORD_RISK_OVER_SUGG'
  | 'CASH_CODE'
  | 'CASHREF'
  | 'USED_IN_PERIODS'
  | 'CONTACT2'
  | 'CONTACT3'
  | 'E_MAIL2'
  | 'E_MAIL3'
  | 'CONTACT1_TEL_CODE'
  | 'CONTACT2_TEL_CODE'
  | 'CONTACT3_TEL_CODE'
  | 'CONTACT1_TEL'
  | 'CONTACT2_TEL'
  | 'CONTACT3_TEL'
  | 'CONTACT1_TEL_EXT'
  | 'CONTACT2_TEL_EXT'
  | 'CONTACT3_TEL_EXT'
  | 'RSKLIM_CNTRL'
  | 'DUEDATE_CNTRL'
  | 'AGING_CNTRL'
  | 'AGING_DAY'
  | 'ORD_PRIORITY'
  | 'ACCEPT_EINV'
  | 'EIVOICEID'
  | 'PROFILE_ID'
  | 'PURC_ORDER_STATUS'
  | 'PURC_ORDER_PRICE'
  | 'BANK_CURR1'
  | 'BANK_CURR2'
  | 'BANK_CURR3'
  | 'BANK_CURR4'
  | 'BANK_CURR5'
  | 'BANK_CURR6'
  | 'BANK_CURR7'
  | 'CS_DOWNS_RISK'
  | 'CST_CS_CIRO_RISK_OVER'
  | 'CST_CIRO_CEK_RISK_FAC'
  | 'CST_CIRO_SENET_RISK_FAC'
  | 'CS_CIRO_DOWNS_RISK'
  | 'CST_CS_CIRO_RISK_LIMIT'
  | 'REP_CST_CS_CIRO_RISK_LIMIT'
  | 'CST_CS_CIRO_RISK_BALANCED'
  | 'REP_CST_CS_CIRO_RISK_BALANCED'
  | 'CST_CS_OWN_RISK_TOTAL'
  | 'REP_CST_CS_OWN_RISK_TOTAL'
  | 'CST_CS_CIRO_RISK_TOTAL'
  | 'REP_CST_CS_CIRO_RISK_TOTAL'
  | 'DESP_RISK_OVER_SUGG'
  | 'DESP_RISK_LIMIT_SUGG'
  | 'REP_DESP_RISK_LIMIT_SUGG'
  | 'DESP_RISK_TOTAL_SUGG'
  | 'REP_DESP_RISK_TOTAL_SUGG'
  | 'DESP_RISK_BALANCED_SUGG'
  | 'REP_DESP_RISK_BALANCED_SUGG'
  | 'DBS_LIMIT1'
  | 'DBS_LIMIT2'
  | 'DBS_LIMIT3'
  | 'DBS_LIMIT4'
  | 'DBS_LIMIT5'
  | 'DBS_LIMIT6'
  | 'DBS_LIMIT7'
  | 'DBS_TOTAL1'
  | 'DBS_TOTAL2'
  | 'DBS_TOTAL3'
  | 'DBS_TOTAL4'
  | 'DBS_TOTAL5'
  | 'DBS_TOTAL6'
  | 'DBS_TOTAL7'
  | 'DBS_BANKNO1'
  | 'DBS_BANKNO2'
  | 'DBS_BANKNO3'
  | 'DBS_BANKNO4'
  | 'DBS_BANKNO5'
  | 'DBS_BANKNO6'
  | 'DBS_BANKNO7'
  | 'DBS_RSKCTRL1'
  | 'DBS_RSKCTRL2'
  | 'DBS_RSKCTRL3'
  | 'DBS_RSKCTRL4'
  | 'DBS_RSKCTRL5'
  | 'DBS_RSKCTRL6'
  | 'DBS_RSKCTRL7'
  | 'DBS_CURR1'
  | 'DBS_CURR2'
  | 'DBS_CURR3'
  | 'DBS_CURR4'
  | 'DBS_CURR5'
  | 'DBS_CURR6'
  | 'DBS_CURR7'
  | 'BANK_CORRP_ACC1'
  | 'BANK_CORRP_ACC2'
  | 'BANK_CORRP_ACC3'
  | 'BANK_CORRP_ACC4'
  | 'BANK_CORRP_ACC5'
  | 'BANK_CORRP_ACC6'
  | 'BANK_CORRP_ACC7'
  | 'BANK_VOEN1'
  | 'BANK_VOEN2'
  | 'BANK_VOEN3'
  | 'BANK_VOEN4'
  | 'BANK_VOEN5'
  | 'BANK_VOEN6'
  | 'BANK_VOEN7'
  | 'EINVOICE_TYPE'
  | 'EARCHIVE_SEND_MODE'
  | 'EARCHIVE_IS_RETAIL_AR_AP'
  | 'TITLE2'
  | 'TELEPHONE_EXTENSION1'
  | 'TELEPHONE_EXTENSION2'
  | 'FAX_EXTENSION'
  | 'GLOBAL_ID'
  | 'ISFOREIGN'
  | 'POST_LABEL'
  | 'SENDER_LABEL'
  | 'DEG_ACTIVE'
  | 'DEG_CURR'
  | 'NAME'
  | 'SURNAME'
  | 'LABEL_INFO'
  | 'DUE_DATE_CONTOL1'
  | 'DUE_DATE_CONTOL2'
  | 'DUE_DATE_CONTOL3'
  | 'DUE_DATE_CONTOL4'
  | 'DUE_DATE_CONTOL5'
  | 'DUE_DATE_CONTOL6'
  | 'DUE_DATE_CONTOL7'
  | 'DUE_DATE_CONTOL8'
  | 'DUE_DATE_CONTOL9'
  | 'DUE_DATE_CONTOL10'
  | 'DUE_DATE_CONTOL11'
  | 'DUE_DATE_CONTOL12'
  | 'DUE_DATE_CONTOL13'
  | 'DUE_DATE_CONTOL14'
  | 'DUE_DATE_CONTOL15'
  | 'DUE_DATE_COUNT'
  | 'DUE_DATE_LIMIT'
  | 'DUE_DATE_TRACK'
  | 'CLOSE_DATE_COUNT'
  | 'CLOSE_DATE_TRACK'
  | 'DEFBNACCREF'
  | 'DEFAULT_BANKACC_CODE'
  | 'CURR_RATE_TYPE'
  | 'INSTEAD_OF_DISPATCH'
  | 'EINV_EARC_TYPE'
  | 'ADDRESS_NO'
  | 'FBS_SEND_METHOD'
  | 'FBS_SEND_EMAILADDR'
  | 'FBS_SEND_FORMAT'
  | 'FBS_SEND_FAXNR'
  | 'FBA_SEND_METHOD'
  | 'FBA_SEND_EMAILADDR'
  | 'FBA_SEND_FORMAT'
  | 'FBA_SEND_FAXNR'
  | 'SECTOR_MAIN_REF'
  | 'SECTOR_MAIN_CODE'
  | 'SECTOR_SUB_REF'
  | 'SECTOR_SUB_CODE'
  | 'PERSONEL_COSTS'
  | 'EARC_EMAIL_ADDRESS1'
  | 'EARC_EMAIL_ADDRESS2'
  | 'EARC_EMAIL_ADDRESS3'
  | 'FACTORY_DIV_NR'
  | 'FACTORY_NR'
  | 'IN_INVEN_NR'
  | 'OUT_INVEN_NR'
  | 'QTY_DEP_DURATION'
  | 'QTY_IN_DEP_DURATION'
  | 'OVER_LAP_TYPE'
  | 'OVER_LAP_AMOUNT'
  | 'OVER_LAP_PERC'
  | 'BROKER_COMP'
  | 'CREATE_WH_FICHE'
  | 'EINV_CUSTOMS'
  | 'SUB_CONT'
  | 'ACCEPT_DESP'
  | 'PROFILEID_DESP'
  | 'LABEL_INFO_DESP'
  | 'POST_LABEL_CODE_DESP'
  | 'SENDER_LABEL_CODE_DESP'
  | 'ACCEPT_EINV_PUBLIC'
  | 'PUBLICBNACCREF'
  | 'PUBLIC_BNACC_CODE'
  | 'PUBLIC_BNACC_IBAN'
  | 'PUBLIC_BNACC_CURRENCY'
  | 'KVKK_PERM_STATUS'
  | 'KVKK_BEGIN_DATE'
  | 'KVKK_END_DATE'
  | 'KVKK_CANCEL_DATE'
  | 'KVKK_ANONYMIZE_STATUS'
  | 'KVKK_ANONYMIZE_DATE'
  | 'EXIM_SEND_METHOD'
  | 'EXIM_SEND_EMAILADR'
  | 'EXIM_SEND_FORMAT'
  | 'EXIM_SEND_FAXNR'
  | 'CAN_DEDUCT'
  | 'DRIVERREF'
  | 'EX_COUNTRY_TYPE'
  | 'EX_COUNTRYREF'
  | 'EX_COUNTRY_CODE'
  | 'EX_COUNTRY_NAME'
  | 'IM_COUNTRY_TYPE'
  | 'IM_COUNTRYREF'
  | 'IM_COUNTRY_CODE'
  | 'IM_COUNTRY_NAME'
  | 'EXIM_PAYTYPEREF'
  | 'EXIM_PAYTYPE_CODE'
  | 'EXIM_BRBANKREF'
  | 'EXIM_BRBANK_CODE'
  | 'EXIM_CUSTOMREF'
  | 'EXIM_CUSTOM_CODE'
  | 'EXIM_REGTYPEREF'
  | 'EXIM_REGTYPE_CODE'
  | 'EXIM_NOTIFYCLREF'
  | 'EXIM_NOTIFY_ARPCODE'
  | 'EXIM_CONSULTCLREF'
  | 'EXIM_CONSULT_ARPCODE'
  | 'EXIM_FREIGHTCLREF'
  | 'EXIM_FREIGHT_ARPCODE'
  | 'DISP_PRINT_CNT'
  | 'ORD_PRINT_CNT'
  | 'GUID'
  | 'CLPTYPEFORPPAYDT'
  | 'CLSTYPEFORPPAYDT'
  | 'MERSIS_NO'
  | 'COMM_RECORD_NO'
  | 'LOW_LEVEL_CODES1'
  | 'LOW_LEVEL_CODES2'
  | 'LOW_LEVEL_CODES3'
  | 'LOW_LEVEL_CODES4'
  | 'LOW_LEVEL_CODES5'
  | 'LOW_LEVEL_CODES6'
  | 'LOW_LEVEL_CODES7'
  | 'LOW_LEVEL_CODES8'
  | 'LOW_LEVEL_CODES9'
  | 'LOW_LEVEL_CODES10'
  | 'INSTAGRAMURL'
  | 'LINKEDINURL'
  | 'WHATSAPPID';

/**
 * Type-safe sort specification for Arps queries
 */
export type ArpsSortSpec =
  | [ArpsField]
  | [ArpsField, 'asc' | 'desc']
  | [ArpsField[], 'asc' | 'desc']
  | [ArpsField[]];

/**
 * Type-safe query options for Arps entities
 *
 * Provides IntelliSense and type safety for:
 * - `fields`: Array of field names to return
 * - `sort`: Simplified sort syntax with field arrays and direction
 *
 * @example
 * ```typescript
 * // Select specific fields
 * const result = await client.getAll({
 *   fields: ['CODE', 'TITLE', 'STATUS']  // ✨ Full IntelliSense
 * });
 *
 * // Sort by single field (ascending by default)
 * const sorted1 = await client.getAll({
 *   sort: ['CODE']  // CODE ascending
 * });
 *
 * // Sort by single field with direction
 * const sorted2 = await client.getAll({
 *   sort: ['TITLE', 'desc']  // TITLE descending
 * });
 *
 * // Sort by multiple fields (same direction)
 * const sorted3 = await client.getAll({
 *   sort: [['TITLE', 'CODE'], 'desc']  // Both descending
 * });
 *
 * // Or just multiple fields ascending
 * const sorted4 = await client.getAll({
 *   sort: [['TITLE', 'CODE']]  // Both ascending
 * });
 * ```
 */
export interface ArpsQueryOptions extends Omit<QueryOptions<ArpsField>, 'fields' | 'sort'> {
  /**
   * Array of field names to include in the response
   * @example ['CODE', 'TITLE', 'STATUS']
   */
  fields?: ArpsField[];

  /**
   * Sort specification:
   * - `['FIELD']` - Single field ascending
   * - `['FIELD', 'desc']` - Single field with direction
   * - `[['FIELD1', 'FIELD2'], 'desc']` - Multiple fields, same direction
   * - `[['FIELD1', 'FIELD2']]` - Multiple fields ascending
   *
   * @example ['CODE'] | ['TITLE', 'desc'] | [['CODE', 'TITLE'], 'desc'] | [['CODE', 'TITLE']]
   */
  sort?: ArpsSortSpec;
}

/**
 * Search criteria for Arps entities
 *
 * Supports both simple values and operator objects:
 *
 * Simple usage (shorthand):
 * ```typescript
 * { code: 'ABC', status: 1 }  // CODE eq 'ABC' and STATUS eq 1
 * ```
 *
 * Operator objects:
 * ```typescript
 * {
 *   code: { like: 'AB*' },           // CODE like 'AB*'
 *   price: { gte: 100, lte: 500 },   // PRICE gte 100 and PRICE lte 500
 *   status: { in: [1, 2, 3] }        // (STATUS eq 1 or STATUS eq 2 or STATUS eq 3)
 * }
 * ```
 *
 * Array values (OR condition):
 * ```typescript
 * { tags: ['A', 'B'] }  // (TAGS eq 'A' or TAGS eq 'B')
 * ```
 */
export interface ArpsSearchCriteria {
  internalReference?: NumberFieldValue;
  recordStatus?: NumberFieldValue;
  accountType?: NumberFieldValue;
  code?: StringFieldValue;
  title?: StringFieldValue;
  auxilCode?: StringFieldValue;
  authCode?: StringFieldValue;
  address1?: StringFieldValue;
  address2?: StringFieldValue;
  districtCode?: StringFieldValue;
  district?: StringFieldValue;
  townCode?: StringFieldValue;
  town?: StringFieldValue;
  cityCode?: StringFieldValue;
  city?: StringFieldValue;
  countryCode?: StringFieldValue;
  country?: StringFieldValue;
  postalCode?: StringFieldValue;
  telephone1?: StringFieldValue;
  telephone1Code?: StringFieldValue;
  telephone2?: StringFieldValue;
  telephone2Code?: StringFieldValue;
  fax?: StringFieldValue;
  faxCode?: StringFieldValue;
  taxId?: StringFieldValue;
  taxOffice?: StringFieldValue;
  taxOfficeCode?: StringFieldValue;
  contact?: StringFieldValue;
  discountRate?: NumberFieldValue;
  extenref?: NumberFieldValue;
  paymentCode?: StringFieldValue;
  paymentref?: NumberFieldValue;
  eMail?: StringFieldValue;
  webUrl?: StringFieldValue;
  facebookUrl?: StringFieldValue;
  twitterUrl?: StringFieldValue;
  appleId?: StringFieldValue;
  skypeId?: StringFieldValue;
  reminderType?: NumberFieldValue;
  reminderEmail?: StringFieldValue;
  reminderFax?: StringFieldValue;
  correspLang?: NumberFieldValue;
  vatId?: StringFieldValue;
  blocked?: NumberFieldValue;
  bankId1?: StringFieldValue;
  bankId2?: StringFieldValue;
  bankId3?: StringFieldValue;
  bankId4?: StringFieldValue;
  bankId5?: StringFieldValue;
  bankId6?: StringFieldValue;
  bankId7?: StringFieldValue;
  bankName1?: StringFieldValue;
  bankName2?: StringFieldValue;
  bankName3?: StringFieldValue;
  bankName4?: StringFieldValue;
  bankName5?: StringFieldValue;
  bankName6?: StringFieldValue;
  bankName7?: StringFieldValue;
  bankAccount1?: StringFieldValue;
  bankAccount2?: StringFieldValue;
  bankAccount3?: StringFieldValue;
  bankAccount4?: StringFieldValue;
  bankAccount5?: StringFieldValue;
  bankAccount6?: StringFieldValue;
  bankAccount7?: StringFieldValue;
  deliveryMethod?: StringFieldValue;
  shipmentAgent?: StringFieldValue;
  currency?: NumberFieldValue;
  textinc?: NumberFieldValue;
  dataSiteid?: NumberFieldValue;
  dataReference?: NumberFieldValue;
  eCommId?: StringFieldValue;
  tradingGrp?: StringFieldValue;
  createdBy?: NumberFieldValue;
  dateCreated?: StringFieldValue;
  hourCreated?: NumberFieldValue;
  minCreated?: NumberFieldValue;
  secCreated?: NumberFieldValue;
  modifiedBy?: NumberFieldValue;
  dateModified?: StringFieldValue;
  hourModified?: NumberFieldValue;
  minModified?: NumberFieldValue;
  secModified?: NumberFieldValue;
  debtTrckType?: NumberFieldValue;
  xrtdifType?: NumberFieldValue;
  notes?: DateFieldValue;
  creditType?: NumberFieldValue;
  creditLimit?: NumberFieldValue;
  creditBalanced?: NumberFieldValue;
  riskfactChq?: NumberFieldValue;
  riskfactPromnt?: NumberFieldValue;
  actionCredhold?: NumberFieldValue;
  xbufs?: StringFieldValue;
  glCode?: StringFieldValue;
  accountref?: NumberFieldValue;
  ohpCode?: StringFieldValue;
  centerref?: NumberFieldValue;
  projectCode?: StringFieldValue;
  projectref?: NumberFieldValue;
  fldals?: StringFieldValue;
  itext?: StringFieldValue;
  langp?: StringFieldValue;
  ppGroupCode?: StringFieldValue;
  xmlAttribute?: NumberFieldValue;
  useRepRisk?: NumberFieldValue;
  riskLimit?: NumberFieldValue;
  riskBalanced?: NumberFieldValue;
  ordSendMethod?: NumberFieldValue;
  ordSendEmail?: StringFieldValue;
  ordSendFax?: StringFieldValue;
  dspSendMethod?: NumberFieldValue;
  dspSendEmail?: StringFieldValue;
  dspSendFax?: StringFieldValue;
  invSendMethod?: NumberFieldValue;
  invSendEmail?: StringFieldValue;
  invSendFax?: StringFieldValue;
  subscriberStatus?: NumberFieldValue;
  subscriberExt?: StringFieldValue;
  autoPaidBank?: StringFieldValue;
  paymentType?: NumberFieldValue;
  lastSendRemLev?: NumberFieldValue;
  extAccFlags?: NumberFieldValue;
  ordSendFormat?: NumberFieldValue;
  dspSendFormat?: NumberFieldValue;
  invSendFormat?: NumberFieldValue;
  remSendFormat?: NumberFieldValue;
  storeCreditCardNo?: StringFieldValue;
  clOrdFreq?: NumberFieldValue;
  ordDay?: NumberFieldValue;
  logoid?: StringFieldValue;
  lidConfirmed?: NumberFieldValue;
  eBsnsSendType?: NumberFieldValue;
  ldxDefOrderStat?: NumberFieldValue;
  ldxDefOrderPrc?: NumberFieldValue;
  itrSendMethod?: NumberFieldValue;
  itrSendMailAdr?: StringFieldValue;
  itrSendFax?: StringFieldValue;
  itrSendFormat?: NumberFieldValue;
  img2inc?: NumberFieldValue;
  cellPhone?: StringFieldValue;
  invoicePrntCnt?: NumberFieldValue;
  geniusfldslist?: DateFieldValue;
  defnfldslist?: DateFieldValue;
  wflowcardref?: NumberFieldValue;
  parentclcode?: StringFieldValue;
  parentclref?: NumberFieldValue;
  codeChanged?: NumberFieldValue;
  collectinv?: NumberFieldValue;
  pieceordinflict?: NumberFieldValue;
  orglogoid?: StringFieldValue;
  purchbrws?: NumberFieldValue;
  salesbrws?: NumberFieldValue;
  impbrws?: NumberFieldValue;
  expbrws?: NumberFieldValue;
  finbrws?: NumberFieldValue;
  collatrlriskType?: NumberFieldValue;
  collriskOver?: NumberFieldValue;
  collriskOrdRiskOver?: NumberFieldValue;
  collriskDespRiskOver?: NumberFieldValue;
  collriskUseRepRisk?: NumberFieldValue;
  collriskPcollatrlTotal?: NumberFieldValue;
  collriskRepPcollatrlTot?: NumberFieldValue;
  collriskScollatrlTotal?: NumberFieldValue;
  collriskTotal?: NumberFieldValue;
  collriskRepRiskTotal?: NumberFieldValue;
  collriskDespTotal?: NumberFieldValue;
  collriskRepDespRiskTot?: NumberFieldValue;
  collriskLimit?: NumberFieldValue;
  collriskRepLimit?: NumberFieldValue;
  collriskBalanced?: NumberFieldValue;
  collriskRepBalanced?: NumberFieldValue;
  collriskOrdRiskTotal?: NumberFieldValue;
  collriskRepOrdRiskTot?: NumberFieldValue;
  collriskOrdRiskTotSugg?: NumberFieldValue;
  collriskRepOrdRiskTotSug?: NumberFieldValue;
  collriskSepCsRiskTot?: NumberFieldValue;
  collriskCsRiskOver?: NumberFieldValue;
  collriskCsRiskTotal?: NumberFieldValue;
  collriskRepCsRiskTot?: NumberFieldValue;
  grpfirmnr?: NumberFieldValue;
  conscoderef?: NumberFieldValue;
  conscode?: StringFieldValue;
  auxilCode2?: StringFieldValue;
  auxilCode3?: StringFieldValue;
  auxilCode4?: StringFieldValue;
  auxilCode5?: StringFieldValue;
  ebankcode?: NumberFieldValue;
  offSendMethod?: NumberFieldValue;
  offSendMailAddr?: StringFieldValue;
  offSendFax?: StringFieldValue;
  offSendFormat?: NumberFieldValue;
  riskType1?: NumberFieldValue;
  riskType2?: NumberFieldValue;
  riskType3?: NumberFieldValue;
  riskType4?: NumberFieldValue;
  riskType5?: NumberFieldValue;
  riskType6?: NumberFieldValue;
  riskType7?: NumberFieldValue;
  riskType8?: NumberFieldValue;
  riskType9?: NumberFieldValue;
  riskType10?: NumberFieldValue;
  riskType11?: NumberFieldValue;
  riskType12?: NumberFieldValue;
  riskType13?: NumberFieldValue;
  riskType14?: NumberFieldValue;
  riskType15?: NumberFieldValue;
  cstCekRiskFactor?: NumberFieldValue;
  cstSenetRiskFactor?: NumberFieldValue;
  riskGrpControl?: NumberFieldValue;
  actionCredholdOrd?: NumberFieldValue;
  actionCredholdDesp?: NumberFieldValue;
  actionCredholdAcc?: NumberFieldValue;
  actionCredholdCstCs?: NumberFieldValue;
  actionCredholdMyCs?: NumberFieldValue;
  riskCtrlType?: NumberFieldValue;
  accRiskTotal?: NumberFieldValue;
  repAccRiskTotal?: NumberFieldValue;
  cstCsRiskTotal?: NumberFieldValue;
  repCstCsRiskTotal?: NumberFieldValue;
  myCsRiskTotal?: NumberFieldValue;
  repMyCsRiskTotal?: NumberFieldValue;
  ordRiskTotal?: NumberFieldValue;
  repOrdRiskTotal?: NumberFieldValue;
  ordRiskTotalSugg?: NumberFieldValue;
  repOrdRiskTotalSugg?: NumberFieldValue;
  despRiskTotal?: NumberFieldValue;
  repDespRiskTotal?: NumberFieldValue;
  accRiskLimit?: NumberFieldValue;
  repAccRiskLimit?: NumberFieldValue;
  cstCsRiskLimit?: NumberFieldValue;
  repCstCsRiskLimit?: NumberFieldValue;
  myCsRiskLimit?: NumberFieldValue;
  repMyCsRiskLimit?: NumberFieldValue;
  despRiskLimit?: NumberFieldValue;
  repDespRiskLimit?: NumberFieldValue;
  ordRiskLimit?: NumberFieldValue;
  repOrdRiskLimit?: NumberFieldValue;
  ordRiskLimitSugg?: NumberFieldValue;
  repOrdSirkLimitSugg?: NumberFieldValue;
  accRiskBalanced?: NumberFieldValue;
  repAccRiskBalanced?: NumberFieldValue;
  cstCsRiskBalanced?: NumberFieldValue;
  repCstCsRiskBalanced?: NumberFieldValue;
  myCsRiskBalanced?: NumberFieldValue;
  repMyCsRiskBalanced?: NumberFieldValue;
  despRiskBalanced?: NumberFieldValue;
  repDespRiskBalanced?: NumberFieldValue;
  ordRiskBalanced?: NumberFieldValue;
  repOrdRiskBalanced?: NumberFieldValue;
  ordRiskBalancedSugg?: NumberFieldValue;
  repOrdRiskBalancedSugg?: NumberFieldValue;
  loanGrpCtrl?: NumberFieldValue;
  ebusDataSendType?: NumberFieldValue;
  iniStatusFlags?: NumberFieldValue;
  slsOrderStatus?: NumberFieldValue;
  slsOrderPrice?: NumberFieldValue;
  sameItemCodeUse?: NumberFieldValue;
  image?: StringFieldValue;
  imageSize?: NumberFieldValue;
  mapId?: StringFieldValue;
  longitude?: StringFieldValue;
  latitude?: StringFieldValue;
  cityId?: StringFieldValue;
  townId?: StringFieldValue;
  bankIban1?: StringFieldValue;
  bankIban2?: StringFieldValue;
  bankIban3?: StringFieldValue;
  bankIban4?: StringFieldValue;
  bankIban5?: StringFieldValue;
  bankIban6?: StringFieldValue;
  bankIban7?: StringFieldValue;
  bankBic1?: StringFieldValue;
  bankBic2?: StringFieldValue;
  bankBic3?: StringFieldValue;
  bankBic4?: StringFieldValue;
  bankBic5?: StringFieldValue;
  bankBic6?: StringFieldValue;
  bankBic7?: StringFieldValue;
  perscompany?: NumberFieldValue;
  tckno?: StringFieldValue;
  extSendMethod?: NumberFieldValue;
  extSendEmail?: StringFieldValue;
  extSendFax?: StringFieldValue;
  extSendFormat?: NumberFieldValue;
  addtoreflist?: NumberFieldValue;
  ordRiskOverSugg?: NumberFieldValue;
  cashCode?: StringFieldValue;
  cashref?: NumberFieldValue;
  usedInPeriods?: NumberFieldValue;
  contact2?: StringFieldValue;
  contact3?: StringFieldValue;
  eMail2?: StringFieldValue;
  eMail3?: StringFieldValue;
  contact1TelCode?: StringFieldValue;
  contact2TelCode?: StringFieldValue;
  contact3TelCode?: StringFieldValue;
  contact1Tel?: StringFieldValue;
  contact2Tel?: StringFieldValue;
  contact3Tel?: StringFieldValue;
  contact1TelExt?: StringFieldValue;
  contact2TelExt?: StringFieldValue;
  contact3TelExt?: StringFieldValue;
  rsklimCntrl?: NumberFieldValue;
  duedateCntrl?: NumberFieldValue;
  agingCntrl?: NumberFieldValue;
  agingDay?: NumberFieldValue;
  ordPriority?: NumberFieldValue;
  acceptEinv?: NumberFieldValue;
  eivoiceid?: StringFieldValue;
  profileId?: NumberFieldValue;
  purcOrderStatus?: NumberFieldValue;
  purcOrderPrice?: NumberFieldValue;
  bankCurr1?: StringFieldValue;
  bankCurr2?: StringFieldValue;
  bankCurr3?: StringFieldValue;
  bankCurr4?: StringFieldValue;
  bankCurr5?: StringFieldValue;
  bankCurr6?: StringFieldValue;
  bankCurr7?: StringFieldValue;
  csDownsRisk?: NumberFieldValue;
  cstCsCiroRiskOver?: NumberFieldValue;
  cstCiroCekRiskFac?: NumberFieldValue;
  cstCiroSenetRiskFac?: NumberFieldValue;
  csCiroDownsRisk?: NumberFieldValue;
  cstCsCiroRiskLimit?: NumberFieldValue;
  repCstCsCiroRiskLimit?: NumberFieldValue;
  cstCsCiroRiskBalanced?: NumberFieldValue;
  repCstCsCiroRiskBalanced?: NumberFieldValue;
  cstCsOwnRiskTotal?: NumberFieldValue;
  repCstCsOwnRiskTotal?: NumberFieldValue;
  cstCsCiroRiskTotal?: NumberFieldValue;
  repCstCsCiroRiskTotal?: NumberFieldValue;
  despRiskOverSugg?: NumberFieldValue;
  despRiskLimitSugg?: NumberFieldValue;
  repDespRiskLimitSugg?: NumberFieldValue;
  despRiskTotalSugg?: NumberFieldValue;
  repDespRiskTotalSugg?: NumberFieldValue;
  despRiskBalancedSugg?: NumberFieldValue;
  repDespRiskBalancedSugg?: NumberFieldValue;
  dbsLimit1?: NumberFieldValue;
  dbsLimit2?: NumberFieldValue;
  dbsLimit3?: NumberFieldValue;
  dbsLimit4?: NumberFieldValue;
  dbsLimit5?: NumberFieldValue;
  dbsLimit6?: NumberFieldValue;
  dbsLimit7?: NumberFieldValue;
  dbsTotal1?: NumberFieldValue;
  dbsTotal2?: NumberFieldValue;
  dbsTotal3?: NumberFieldValue;
  dbsTotal4?: NumberFieldValue;
  dbsTotal5?: NumberFieldValue;
  dbsTotal6?: NumberFieldValue;
  dbsTotal7?: NumberFieldValue;
  dbsBankno1?: NumberFieldValue;
  dbsBankno2?: NumberFieldValue;
  dbsBankno3?: NumberFieldValue;
  dbsBankno4?: NumberFieldValue;
  dbsBankno5?: NumberFieldValue;
  dbsBankno6?: NumberFieldValue;
  dbsBankno7?: NumberFieldValue;
  dbsRskctrl1?: NumberFieldValue;
  dbsRskctrl2?: NumberFieldValue;
  dbsRskctrl3?: NumberFieldValue;
  dbsRskctrl4?: NumberFieldValue;
  dbsRskctrl5?: NumberFieldValue;
  dbsRskctrl6?: NumberFieldValue;
  dbsRskctrl7?: NumberFieldValue;
  dbsCurr1?: NumberFieldValue;
  dbsCurr2?: NumberFieldValue;
  dbsCurr3?: NumberFieldValue;
  dbsCurr4?: NumberFieldValue;
  dbsCurr5?: NumberFieldValue;
  dbsCurr6?: NumberFieldValue;
  dbsCurr7?: NumberFieldValue;
  bankCorrpAcc1?: StringFieldValue;
  bankCorrpAcc2?: StringFieldValue;
  bankCorrpAcc3?: StringFieldValue;
  bankCorrpAcc4?: StringFieldValue;
  bankCorrpAcc5?: StringFieldValue;
  bankCorrpAcc6?: StringFieldValue;
  bankCorrpAcc7?: StringFieldValue;
  bankVoen1?: StringFieldValue;
  bankVoen2?: StringFieldValue;
  bankVoen3?: StringFieldValue;
  bankVoen4?: StringFieldValue;
  bankVoen5?: StringFieldValue;
  bankVoen6?: StringFieldValue;
  bankVoen7?: StringFieldValue;
  einvoiceType?: NumberFieldValue;
  earchiveSendMode?: NumberFieldValue;
  earchiveIsRetailArAp?: NumberFieldValue;
  title2?: StringFieldValue;
  telephoneExtension1?: StringFieldValue;
  telephoneExtension2?: StringFieldValue;
  faxExtension?: StringFieldValue;
  globalId?: StringFieldValue;
  isforeign?: NumberFieldValue;
  postLabel?: StringFieldValue;
  senderLabel?: StringFieldValue;
  degActive?: NumberFieldValue;
  degCurr?: NumberFieldValue;
  name?: StringFieldValue;
  surname?: StringFieldValue;
  labelInfo?: NumberFieldValue;
  dueDateContol1?: NumberFieldValue;
  dueDateContol2?: NumberFieldValue;
  dueDateContol3?: NumberFieldValue;
  dueDateContol4?: NumberFieldValue;
  dueDateContol5?: NumberFieldValue;
  dueDateContol6?: NumberFieldValue;
  dueDateContol7?: NumberFieldValue;
  dueDateContol8?: NumberFieldValue;
  dueDateContol9?: NumberFieldValue;
  dueDateContol10?: NumberFieldValue;
  dueDateContol11?: NumberFieldValue;
  dueDateContol12?: NumberFieldValue;
  dueDateContol13?: NumberFieldValue;
  dueDateContol14?: NumberFieldValue;
  dueDateContol15?: NumberFieldValue;
  dueDateCount?: NumberFieldValue;
  dueDateLimit?: NumberFieldValue;
  dueDateTrack?: NumberFieldValue;
  closeDateCount?: NumberFieldValue;
  closeDateTrack?: NumberFieldValue;
  defbnaccref?: NumberFieldValue;
  defaultBankaccCode?: StringFieldValue;
  currRateType?: NumberFieldValue;
  insteadOfDispatch?: NumberFieldValue;
  einvEarcType?: NumberFieldValue;
  addressNo?: StringFieldValue;
  fbsSendMethod?: NumberFieldValue;
  fbsSendEmailaddr?: StringFieldValue;
  fbsSendFormat?: NumberFieldValue;
  fbsSendFaxnr?: StringFieldValue;
  fbaSendMethod?: NumberFieldValue;
  fbaSendEmailaddr?: StringFieldValue;
  fbaSendFormat?: NumberFieldValue;
  fbaSendFaxnr?: StringFieldValue;
  sectorMainRef?: NumberFieldValue;
  sectorMainCode?: StringFieldValue;
  sectorSubRef?: NumberFieldValue;
  sectorSubCode?: StringFieldValue;
  personelCosts?: NumberFieldValue;
  earcEmailAddress1?: StringFieldValue;
  earcEmailAddress2?: StringFieldValue;
  earcEmailAddress3?: StringFieldValue;
  factoryDivNr?: NumberFieldValue;
  factoryNr?: NumberFieldValue;
  inInvenNr?: NumberFieldValue;
  outInvenNr?: NumberFieldValue;
  qtyDepDuration?: NumberFieldValue;
  qtyInDepDuration?: NumberFieldValue;
  overLapType?: NumberFieldValue;
  overLapAmount?: NumberFieldValue;
  overLapPerc?: NumberFieldValue;
  brokerComp?: NumberFieldValue;
  createWhFiche?: NumberFieldValue;
  einvCustoms?: NumberFieldValue;
  subCont?: NumberFieldValue;
  acceptDesp?: NumberFieldValue;
  profileidDesp?: NumberFieldValue;
  labelInfoDesp?: NumberFieldValue;
  postLabelCodeDesp?: StringFieldValue;
  senderLabelCodeDesp?: StringFieldValue;
  acceptEinvPublic?: NumberFieldValue;
  publicbnaccref?: NumberFieldValue;
  publicBnaccCode?: StringFieldValue;
  publicBnaccIban?: StringFieldValue;
  publicBnaccCurrency?: NumberFieldValue;
  kvkkPermStatus?: NumberFieldValue;
  kvkkBeginDate?: StringFieldValue;
  kvkkEndDate?: StringFieldValue;
  kvkkCancelDate?: StringFieldValue;
  kvkkAnonymizeStatus?: NumberFieldValue;
  kvkkAnonymizeDate?: StringFieldValue;
  eximSendMethod?: NumberFieldValue;
  eximSendEmailadr?: StringFieldValue;
  eximSendFormat?: NumberFieldValue;
  eximSendFaxnr?: StringFieldValue;
  canDeduct?: NumberFieldValue;
  driverref?: NumberFieldValue;
  exCountryType?: NumberFieldValue;
  exCountryref?: NumberFieldValue;
  exCountryCode?: StringFieldValue;
  exCountryName?: StringFieldValue;
  imCountryType?: NumberFieldValue;
  imCountryref?: NumberFieldValue;
  imCountryCode?: StringFieldValue;
  imCountryName?: StringFieldValue;
  eximPaytyperef?: NumberFieldValue;
  eximPaytypeCode?: StringFieldValue;
  eximBrbankref?: NumberFieldValue;
  eximBrbankCode?: StringFieldValue;
  eximCustomref?: NumberFieldValue;
  eximCustomCode?: StringFieldValue;
  eximRegtyperef?: NumberFieldValue;
  eximRegtypeCode?: StringFieldValue;
  eximNotifyclref?: NumberFieldValue;
  eximNotifyArpcode?: StringFieldValue;
  eximConsultclref?: NumberFieldValue;
  eximConsultArpcode?: StringFieldValue;
  eximFreightclref?: NumberFieldValue;
  eximFreightArpcode?: StringFieldValue;
  dispPrintCnt?: NumberFieldValue;
  ordPrintCnt?: NumberFieldValue;
  guid?: StringFieldValue;
  clptypeforppaydt?: NumberFieldValue;
  clstypeforppaydt?: NumberFieldValue;
  mersisNo?: StringFieldValue;
  commRecordNo?: StringFieldValue;
  lowLevelCodes1?: NumberFieldValue;
  lowLevelCodes2?: NumberFieldValue;
  lowLevelCodes3?: NumberFieldValue;
  lowLevelCodes4?: NumberFieldValue;
  lowLevelCodes5?: NumberFieldValue;
  lowLevelCodes6?: NumberFieldValue;
  lowLevelCodes7?: NumberFieldValue;
  lowLevelCodes8?: NumberFieldValue;
  lowLevelCodes9?: NumberFieldValue;
  lowLevelCodes10?: NumberFieldValue;
  instagramurl?: StringFieldValue;
  linkedinurl?: StringFieldValue;
  whatsappid?: StringFieldValue;

  // Index signature for compatibility with utility SearchCriteria type
  [key: string]: AllFieldValues;
}

/**
 * Analytics data for Arps entities
 */
export interface ArpsAnalytics {
  total: number;
  // Add Arps-specific analytics fields
}
